/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as TodayRouteImport } from "./routes/today"
import { Route as AuthenticatedRouteRouteImport } from "./routes/_authenticated/route"
import { Route as AuthenticatedIndexRouteImport } from "./routes/_authenticated/index"
import { Route as AuthVerifyEmailRouteImport } from "./routes/auth/verify-email"
import { Route as AuthResetPasswordRouteImport } from "./routes/auth/reset-password"
import { Route as AuthRequestPasswordResetRouteImport } from "./routes/auth/request-password-reset"
import { Route as AuthRegisterRouteImport } from "./routes/auth/register"
import { Route as AuthLoginRouteImport } from "./routes/auth/login"
import { Route as AuthAccountRouteImport } from "./routes/auth/account"
import { Route as AuthenticatedActivitiesIndexRouteImport } from "./routes/_authenticated/activities/index"
import { Route as AuthenticatedNotesNewRouteImport } from "./routes/_authenticated/notes/new"
import { Route as AuthenticatedHabitsNewRouteImport } from "./routes/_authenticated/habits/new"
import { Route as AuthenticatedActivitiesNewRouteImport } from "./routes/_authenticated/activities/new"

const TodayRoute = TodayRouteImport.update({
  id: "/today",
  path: "/today",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: "/auth/verify-email",
  path: "/auth/verify-email",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: "/auth/reset-password",
  path: "/auth/reset-password",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRequestPasswordResetRoute =
  AuthRequestPasswordResetRouteImport.update({
    id: "/auth/request-password-reset",
    path: "/auth/request-password-reset",
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: "/auth/register",
  path: "/auth/register",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: "/auth/login",
  path: "/auth/login",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAccountRoute = AuthAccountRouteImport.update({
  id: "/auth/account",
  path: "/auth/account",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedActivitiesIndexRoute =
  AuthenticatedActivitiesIndexRouteImport.update({
    id: "/activities/",
    path: "/activities/",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotesNewRoute = AuthenticatedNotesNewRouteImport.update({
  id: "/notes/new",
  path: "/notes/new",
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHabitsNewRoute = AuthenticatedHabitsNewRouteImport.update({
  id: "/habits/new",
  path: "/habits/new",
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActivitiesNewRoute =
  AuthenticatedActivitiesNewRouteImport.update({
    id: "/activities/new",
    path: "/activities/new",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/today": typeof TodayRoute
  "/auth/account": typeof AuthAccountRoute
  "/auth/login": typeof AuthLoginRoute
  "/auth/register": typeof AuthRegisterRoute
  "/auth/request-password-reset": typeof AuthRequestPasswordResetRoute
  "/auth/reset-password": typeof AuthResetPasswordRoute
  "/auth/verify-email": typeof AuthVerifyEmailRoute
  "/": typeof AuthenticatedIndexRoute
  "/activities/new": typeof AuthenticatedActivitiesNewRoute
  "/habits/new": typeof AuthenticatedHabitsNewRoute
  "/notes/new": typeof AuthenticatedNotesNewRoute
  "/activities": typeof AuthenticatedActivitiesIndexRoute
}
export interface FileRoutesByTo {
  "/today": typeof TodayRoute
  "/auth/account": typeof AuthAccountRoute
  "/auth/login": typeof AuthLoginRoute
  "/auth/register": typeof AuthRegisterRoute
  "/auth/request-password-reset": typeof AuthRequestPasswordResetRoute
  "/auth/reset-password": typeof AuthResetPasswordRoute
  "/auth/verify-email": typeof AuthVerifyEmailRoute
  "/": typeof AuthenticatedIndexRoute
  "/activities/new": typeof AuthenticatedActivitiesNewRoute
  "/habits/new": typeof AuthenticatedHabitsNewRoute
  "/notes/new": typeof AuthenticatedNotesNewRoute
  "/activities": typeof AuthenticatedActivitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/_authenticated": typeof AuthenticatedRouteRouteWithChildren
  "/today": typeof TodayRoute
  "/auth/account": typeof AuthAccountRoute
  "/auth/login": typeof AuthLoginRoute
  "/auth/register": typeof AuthRegisterRoute
  "/auth/request-password-reset": typeof AuthRequestPasswordResetRoute
  "/auth/reset-password": typeof AuthResetPasswordRoute
  "/auth/verify-email": typeof AuthVerifyEmailRoute
  "/_authenticated/": typeof AuthenticatedIndexRoute
  "/_authenticated/activities/new": typeof AuthenticatedActivitiesNewRoute
  "/_authenticated/habits/new": typeof AuthenticatedHabitsNewRoute
  "/_authenticated/notes/new": typeof AuthenticatedNotesNewRoute
  "/_authenticated/activities/": typeof AuthenticatedActivitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/today"
    | "/auth/account"
    | "/auth/login"
    | "/auth/register"
    | "/auth/request-password-reset"
    | "/auth/reset-password"
    | "/auth/verify-email"
    | "/"
    | "/activities/new"
    | "/habits/new"
    | "/notes/new"
    | "/activities"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/today"
    | "/auth/account"
    | "/auth/login"
    | "/auth/register"
    | "/auth/request-password-reset"
    | "/auth/reset-password"
    | "/auth/verify-email"
    | "/"
    | "/activities/new"
    | "/habits/new"
    | "/notes/new"
    | "/activities"
  id:
    | "__root__"
    | "/_authenticated"
    | "/today"
    | "/auth/account"
    | "/auth/login"
    | "/auth/register"
    | "/auth/request-password-reset"
    | "/auth/reset-password"
    | "/auth/verify-email"
    | "/_authenticated/"
    | "/_authenticated/activities/new"
    | "/_authenticated/habits/new"
    | "/_authenticated/notes/new"
    | "/_authenticated/activities/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  TodayRoute: typeof TodayRoute
  AuthAccountRoute: typeof AuthAccountRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthRequestPasswordResetRoute: typeof AuthRequestPasswordResetRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/today": {
      id: "/today"
      path: "/today"
      fullPath: "/today"
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authenticated": {
      id: "/_authenticated"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authenticated/": {
      id: "/_authenticated/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    "/auth/verify-email": {
      id: "/auth/verify-email"
      path: "/auth/verify-email"
      fullPath: "/auth/verify-email"
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/auth/reset-password": {
      id: "/auth/reset-password"
      path: "/auth/reset-password"
      fullPath: "/auth/reset-password"
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/auth/request-password-reset": {
      id: "/auth/request-password-reset"
      path: "/auth/request-password-reset"
      fullPath: "/auth/request-password-reset"
      preLoaderRoute: typeof AuthRequestPasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/auth/register": {
      id: "/auth/register"
      path: "/auth/register"
      fullPath: "/auth/register"
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/auth/login": {
      id: "/auth/login"
      path: "/auth/login"
      fullPath: "/auth/login"
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/auth/account": {
      id: "/auth/account"
      path: "/auth/account"
      fullPath: "/auth/account"
      preLoaderRoute: typeof AuthAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authenticated/activities/": {
      id: "/_authenticated/activities/"
      path: "/activities"
      fullPath: "/activities"
      preLoaderRoute: typeof AuthenticatedActivitiesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    "/_authenticated/notes/new": {
      id: "/_authenticated/notes/new"
      path: "/notes/new"
      fullPath: "/notes/new"
      preLoaderRoute: typeof AuthenticatedNotesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    "/_authenticated/habits/new": {
      id: "/_authenticated/habits/new"
      path: "/habits/new"
      fullPath: "/habits/new"
      preLoaderRoute: typeof AuthenticatedHabitsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    "/_authenticated/activities/new": {
      id: "/_authenticated/activities/new"
      path: "/activities/new"
      fullPath: "/activities/new"
      preLoaderRoute: typeof AuthenticatedActivitiesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedActivitiesNewRoute: typeof AuthenticatedActivitiesNewRoute
  AuthenticatedHabitsNewRoute: typeof AuthenticatedHabitsNewRoute
  AuthenticatedNotesNewRoute: typeof AuthenticatedNotesNewRoute
  AuthenticatedActivitiesIndexRoute: typeof AuthenticatedActivitiesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedActivitiesNewRoute: AuthenticatedActivitiesNewRoute,
  AuthenticatedHabitsNewRoute: AuthenticatedHabitsNewRoute,
  AuthenticatedNotesNewRoute: AuthenticatedNotesNewRoute,
  AuthenticatedActivitiesIndexRoute: AuthenticatedActivitiesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  TodayRoute: TodayRoute,
  AuthAccountRoute: AuthAccountRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthRequestPasswordResetRoute: AuthRequestPasswordResetRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
