services:
  store:
    container_name: track-store
    image: redis
    command: /bin/sh -c "redis-server /usr/local/etc/redis/redis.conf --appendonly yes --requirepass $$REDIS_PASS"
    volumes:
      - ./redis-data:/data
      - ./config/redis.conf:/usr/local/etc/redis.conf

  database:
    container_name: track-database
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=$PG_PASS
      - POSTGRES_USER=$PG_USER
      - POSTGRES_DB=$PG_DB
    volumes:
      - ./pg-data:/var/lib/postgresql/data
      - ./config/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - ./config/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      #  - ./database-setup:/docker-entrypoint-initdb.d
      #    I'm not sure if this works. If we try to run the containers on a
      #    new machine and it doesn't, this is the place to check. :) Can
      #    always move the scripts from /server to the old ./database-setup
      #    folder (see commented line above) to initialize the database
      #    anyway, so it's not a big deal. Don't forget to do the same for the
      #    test-database container below!
      - ../server/src/db/scripts:/docker-entrypoint-initdb.d
      - ./database-backup:/psql-backups
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "log_statement=all"]

  server:
    container_name: track-server
    image: seerden/track:latest
    depends_on:
      - database
      - store
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - SERVER_PORT=5000
      - IS_TEST_ENVIRONMENT=false
      - DOMAIN=track.seerden.dev
    env_file:
      - ../server/.env
    command: ["node", "./dist/server.js"] 

  nginx:
      container_name: track-nginx
      image: nginx:latest
      ports:
        - "80:80" 
        - "443:443"
      depends_on:
        - server
      volumes:
        - ../nginx.conf:/etc/nginx/conf.d/default.conf:ro 
        - /etc/letsencrypt/:/etc/letsencrypt
      restart: always