import { Tag } from "./tag.types";
import { ID, Timestamp } from "./utility.types";

/** An activity without autogenerated fields or tag/(sub)category ids. */
export type NewActivity = {
	user_id: ID;
	name: string;
	description: string;
	started_at?: Timestamp;
	ended_at?: Timestamp;
	start_date?: string; // YYYYMMDD
	end_date?: string;
	duration_milliseconds?: number; // in milliseconds
};

/** An activity with autogenerated fields. */
export type Activity = NewActivity & {
	activity_id: ID;
	created_at: Timestamp;
};

/** An activity with (joined) tag fields. */
export type ActivityWithTags = Activity & {
	tags: Tag[]; // many-to-many
	category_id?: ID; // a category is just a tag
	subcategory_id?: ID; // same as a category, but the user decides it's a subcategory
};
