import { TagWithIds } from "./tag.types";
import { ID, Timestamp } from "./utility.types";

/** An activity without autogenerated fields or tag/(sub)category ids. */
export type NewActivity = {
	user_id: ID;
	name: string;
	description: string;
	started_at?: Timestamp;
	ended_at?: Timestamp;
	start_date?: string; // YYYYMMDD
	end_date?: string;
	duration_milliseconds?: number; // in milliseconds
	is_task?: boolean;
	completed_at?: Timestamp; // this probably shouldn't be in this type
	completed?: boolean; // this also probably shouldn't be in this type
};

/** An activity with autogenerated fields. */
export type Activity = NewActivity & {
	activity_id: ID;
	created_at: Timestamp;
};

/** An activity with (joined) tag fields. */
export type ActivityWithTags = Activity & {
	tags: TagWithIds[]; // many-to-many
};
