-- this is a slightly modified version of the CLI `auth:generate` output.
create table
   "auth"."user" (
      "id" integer not null primary key generated by default as identity,
      "name" text not null,
      "email" text not null unique,
      "emailVerified" integer not null,
      "image" text,
      "createdAt" timestamp with time zone not null default now(),
      "updatedAt" timestamp with time zone not null default now(),
      "role" text,
      "banned" integer,
      "banReason" text,
      "banExpires" timestamp with time zone,
      "username" text unique,
      "displayUsername" text
   );

create table
   "auth"."session" (
      "id" integer not null primary key generated by default as identity,
      "expiresAt" timestamp with time zone not null,
      "token" text not null unique,
      "createdAt" timestamp with time zone not null,
      "updatedAt" timestamp with time zone not null,
      "ipAddress" text,
      "userAgent" text,
      "userId" integer not null references "auth"."user" ("id") on delete cascade,
      "impersonatedBy" text
   );

create table
   "auth"."account" (
      "id" integer not null primary key generated by default as identity,
      "accountId" text not null,
      "providerId" text not null,
      "userId" integer not null references "auth"."user" ("id") on delete cascade,
      "accessToken" text,
      "refreshToken" text,
      "idToken" text,
      "accessTokenExpiresAt" timestamp with time zone,
      "refreshTokenExpiresAt" timestamp with time zone,
      "scope" text,
      "password" text,
      "createdAt" timestamp with time zone not null default now(),
      "updatedAt" timestamp with time zone not null
   );

create table
   "auth"."verification" (
      "id" integer not null primary key generated by default as identity,
      "identifier" text not null,
      "value" text not null,
      "expiresAt" timestamp with time zone not null,
      "createdAt" timestamp with time zone not null default now(),
      "updatedAt" timestamp with time zone not null default now()
   );

create index if not exists "session_userId_idx" on "auth"."session" ("userId");

create index if not exists "account_userId_idx" on "auth"."account" ("userId");

create index if not exists "verification_identifier_idx" on "auth"."verification" ("identifier");